### ISSUE TITLE
How do you make test set？

### ISSUE THREAD

**Issue by ztf-ucas** [berkandemirel/zsd#1]
Thanks for your remarkable work! But I have a question: 
On fashion-zsd and pascal-zsd dataset, the test set contains only unseen classes or includes both of seen and unseen classes?

**Comment by berkandemirel** [comment]
Thank you for your interest. All details about experiments are explained in the paper. You can check out Section 4.3 and 4.4 for details. Briefly, we tried all the scenarios.

**Comment by ztf-ucas** [comment]
Thank you very much! I downloaded this dataset, but I found bounding boxes are not consistent with those in your sample image. That is to say, bounding boxes in this dataset are not attached to the edge of objects.

**Comment by berkandemirel** [comment]
You are right about bounding boxes. Edges are not "perfectly" matched with the bounding boxes because this is not human labeled dataset. The original dataset (i.e. fashion-mnist) is also being used for classification and I tried to place those objects on an image, so mismatches with edges of objects are normal.

Moreover, I also publish dataset generation script (i.e. genDataset.py). You can check it out.

**Comment by ztf-ucas** [comment]
> You are right about bounding boxes. Edges are not "perfectly" matched with the bounding boxes because this is not human labeled dataset. The original dataset (i.e. fashion-mnist) is also being used for classification and I tried to place those objects on an image, so mismatches with edges of objects are normal.
> 
> Moreover, I also publish dataset generation script (i.e. genDataset.py). You can check it out.

Thank you very much! I got it!
